{
  if (!renameSupported())   return;
  Path src=getTestRootPath(fc,"test/hadoop/file");
  createFile(src);
  Path dst=getTestRootPath(fc,"test/new/existingFile");
  createFile(dst);
  try {
    rename(src,dst,false,true,false,Rename.NONE);
    Assert.fail("Expected exception was not thrown");
  }
 catch (  IOException e) {
    Assert.assertTrue(unwrapException(e) instanceof FileAlreadyExistsException);
  }
  rename(src,dst,true,false,true,Rename.OVERWRITE);
}
