{
  Configuration conf=new Configuration();
  conf.set("hadoop.security.authentication","kerberos");
  UserGroupInformation.setConfiguration(conf);
  final File testDir=getTestDir();
  conf=createBaseKMSConf(testDir);
  conf.set("hadoop.kms.authentication.type","kerberos");
  conf.set("hadoop.kms.authentication.kerberos.keytab",keytab.getAbsolutePath());
  conf.set("hadoop.kms.authentication.kerberos.principal","HTTP/localhost");
  conf.set("hadoop.kms.authentication.kerberos.name.rules","DEFAULT");
  conf.set("hadoop.kms.proxyuser.client.users","foo");
  conf.set("hadoop.kms.proxyuser.client.hosts","*");
  writeConf(testDir,conf);
  runServer(null,null,testDir,new KMSCallable(){
    @Override public Void call() throws Exception {
      final Configuration conf=new Configuration();
      conf.setInt(KeyProvider.DEFAULT_BITLENGTH_NAME,64);
      final URI uri=createKMSUri(getKMSUrl());
      final UserGroupInformation clientUgi=UserGroupInformation.loginUserFromKeytabAndReturnUGI("client",keytab.getAbsolutePath());
      clientUgi.doAs(new PrivilegedExceptionAction<Void>(){
        @Override public Void run() throws Exception {
          final KeyProvider kp=new KMSClientProvider(uri,conf);
          kp.createKey("kAA",new KeyProvider.Options(conf));
          UserGroupInformation fooUgi=UserGroupInformation.createProxyUser("foo",clientUgi);
          fooUgi.doAs(new PrivilegedExceptionAction<Void>(){
            @Override public Void run() throws Exception {
              Assert.assertNotNull(kp.createKey("kBB",new KeyProvider.Options(conf)));
              return null;
            }
          }
);
          UserGroupInformation foo1Ugi=UserGroupInformation.createProxyUser("foo1",clientUgi);
          foo1Ugi.doAs(new PrivilegedExceptionAction<Void>(){
            @Override public Void run() throws Exception {
              try {
                kp.createKey("kCC",new KeyProvider.Options(conf));
                Assert.fail();
              }
 catch (              AuthorizationException ex) {
              }
catch (              Exception ex) {
                Assert.fail(ex.getMessage());
              }
              return null;
            }
          }
);
          return null;
        }
      }
);
      return null;
    }
  }
);
}
