{
  if (!renameSupported())   return;
  Path src=getTestRootPath(fc,"test/hadoop/dir");
  fc.mkdir(src,FileContext.DEFAULT_PERM,true);
  createFile(getTestRootPath(fc,"test/hadoop/dir/file1"));
  createFile(getTestRootPath(fc,"test/hadoop/dir/subdir/file2"));
  Path dst=getTestRootPath(fc,"test/new/newdir");
  fc.mkdir(dst,FileContext.DEFAULT_PERM,true);
  try {
    rename(src,dst,false,true,false,Rename.NONE);
    Assert.fail("Expected exception was not thrown");
  }
 catch (  IOException e) {
    Assert.assertTrue(unwrapException(e) instanceof FileAlreadyExistsException);
  }
  rename(src,dst,true,false,true,Rename.OVERWRITE);
}
