{
  try {
    this.stop();
  }
 catch (  Exception ex) {
    LOG.warn("Encountered exception when handling exception (" + e.getMessage() + "):",ex);
  }
}
