{
  try {
    application.recover(state);
  }
 catch (  Exception e) {
    LOG.error("Error recovering application",e);
    throw new YarnException(e);
  }
}
